### ISSUE TITLE
Fix native IncomingSocketThreadTest

### ISSUE THREAD

**Issue by evabishchevich** [thaliproject/Thali_CordovaPlugin#1196]

**Comment by evabishchevich** [comment]
Marcin said that there are some updates for this test in vNext. We'll get them in process of merging

**Comment by evabishchevich** [comment]
We still have problems with this test after merge with vNext

**Comment by evabishchevich** [comment]
Fixed. Provided comments 
https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812_1205/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L64

https://github.com/thaliproject/Thali_CordovaPlugin/blob/vNext_yarong_417_812_1205/src/android/test/io/jxcore/node/IncomingSocketThreadTest.java#L223

**Comment by yaronyg** [comment]
Please confirm that this is done.

**Comment by vasilevskayaem** [comment]
not fixed during Friday discussion: StreamCopyingThread contains run() method with while loop. Inside this loop we can get ioException and app won't send data back, so test fails, because we don't receive back data that was sent.

**Comment by vasilevskayaem** [comment]
not fixed during Friday discussion: StreamCopyingThread contains run() method with while loop. Inside this loop we can get ioException and app won't send data back, so test fails, because we don't receive back data that was sent.

**Comment by yaronyg** [comment]
It's not worth fixing this right now. Please disable and move this bug to icebox.
