### ISSUE TITLE
Thali replication issues during integration

### ISSUE THREAD

**Issue by larryonoff** [thaliproject/Thali_CordovaPlugin#1257]
@czyzm provided us with the following issue.

When I start Thali (create ThaliManager and start it) on two devices they discover each other. After that when I do a change on DB on one device this is replicated to other DB. Next changes are also replicated but I am getting error in log:
```
ERROR thaliSendNotificationBasedOnReplication: 'Got an error on the replication change listener - {"name":"AssertionError","actual":null,"expected":true,"operator":"==","message":"If beacons werepreviously updated then there has to be a refresh timer for them.","stack":"ok@assert.js:126:1\nThaliSendNotificationBasedOnReplication.prototype._setUpChangeListener/this._replicationPromise</self._transientState.pouchDBChangesCancelObject<@/data/data/com.rockwellautomation.AppPlatform/files/www/jxcore/node_modules/thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js:364:9\nPouchDBGenerator/PouchAlt.prototype.addListener/<@/data/data/com.rockwellautomation.AppPlatform/files/www/jxcore/node_modules/thali/NextGeneration/utils/pouchDBGenerator.js:101:9"}'
```

The strange thing is that when I wait for some time and do another change I also see the same error in log but then changes are not replicating any more.
I need to turn off and on thali on the other device so that its availability is refreshed
The error comes from the fact that at the beginning (after devices discover each other) there is a call to `_updateOnExpiration` with negative value which is clearing the `beaconRefreshTimerManager`.

**Comment by mlesnic** [comment]
Sometime I also get an error from pouchDBGenerator.

`
E/jxcore-log: Trace: 
at $3.prototype.trace@console.js:139:8
at addListener@events.js:140:1
at PouchDBGenerator/PouchAlt.prototype.addListener@/data/data/com.rockwellautomation.AppPlatform/files/www/jxcore/node_modules/thali/NextGeneration/utils/pouchDBGenerator.js:99:1
at once@events.js:165:1
at Changes@/data/data/com.rockwellautomation.AppPlatform/files/www/jxcore/node_modules/pouchdb/lib/index.js:1442:3
at AbstractPouchDB.prototype.changes@/data/data/com.rockwellautomation.AppPlatform/files/www/jxcore/node_modules/pouchdb/lib/index.js:2373:10`

**Comment by chapko** [comment]
> ```
> ERROR thaliSendNotificationBasedOnReplication: 'Got an error on the replication change listener - {"name":"AssertionError","actual":null,"expected":true,"operator":"==","message":"If beacons werepreviously updated then there has to be a refresh timer for them.","stack":"ok@assert.js:126:1\nThaliSendNotificationBasedOnReplication.prototype._setUpChangeListener/this._replicationPromise</self._transientState.pouchDBChangesCancelObject<@/data/data/com.rockwellautomation.AppPlatform/files/www/jxcore/node_modules/thali/NextGeneration/replication/thaliSendNotificationBasedOnReplication.js:364:9\nPouchDBGenerator/PouchAlt.prototype.addListener/<@/data/data/com.rockwellautomation.AppPlatform/files/www/jxcore/node_modules/thali/NextGeneration/utils/pouchDBGenerator.js:101:9"}'
> ```

It is known bug and probably was fixed by #1248

**Comment by czyzm** [comment]
With the fix from #1248 we do not see the thaliSendNotificationBasedOnReplication error and the synchronization is working!
We are still seeing from time to time the PouchDBGenerator errror in logs. Sync is working despite it.

**Comment by chapko** [comment]
@mlesnic I think this is a part of warning message which should start with something like
```
E/jxcore-log: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```
In this case it's just a warning telling you that you added more than a maximum (10 by default) event listeners to one of the events

**Comment by chapko** [comment]
I just created issue #1259 for the memory leak warning

**Comment by larryonoff** [comment]
Closing this issue since thaliproject/Thali_CordovaPlugin#1248. thaliproject/Thali_CordovaPlugin#1259 is another issue.
