### ISSUE TITLE
Who is eating our connections?

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/Thali_CordovaPlugin#1492]
Someone is sitting on our connections and making us run out. Who is it?

**Comment by andrew-aladev** [comment]
We need to destroy free sockets explicitly. Related to https://github.com/request/forever-agent/issues/30

**Comment by andrew-aladev** [comment]
We've fixed forever agent and now our test can be stopped only because of `jxcore` segfault. I had about 300 dead sockets on Friday after 10 rounds and now I have only 2 dead sockets. Something was not closed properly. I think we can reopen this issue with lower priority.

**Comment by larryonoff** [comment]
We've created our fork of forever-agent, see [thaliproject/forever-agent](https://github.com/thaliproject/forever-agent).

**Comment by yaronyg** [comment]
@larryonoff I thought @andrew-aladev said we still have a slow leak and should keep this issue open but at a lower priority since the leak looks quite slow?

**Comment by larryonoff** [comment]
@yarong we still have leak, but very slow. It least as we know now. So I'm reopening the issue but lower the priority.
